name: Build Chrome Extension ZIP

on:
  workflow_dispatch:

permissions: 
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: chrome-web-store
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: 24
      - name: Install Typescript
        run: npm ci
      - name: Compile Typescript
        run: npm run build
      - name: Create ZIP
        run: |
          zip -r extension.zip . -i "manifest.json" \
          "popup.html" \
          "popup.css" \
          "src/popup.js" \
          "images/*" \
          "_locales/*"
