name: Build Chrome Extension ZIP to Web Store

on:
  workflow_dispatch:

permissions: 
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version: 24
      - name: Install Typescript
        run: npm ci
      - name: Compile Typescript
        run: npm run build
      - name: Create ZIP
        run: |
          zip -r extension.zip . -i "manifest.json" \
          "popup.html" \
          "popup.css" \
          "src/popup.js" \
          "images/*" \
          "_locales/*"
  upload-chrome:
    runs-on: ubuntu-24.04
    environment: chrome-web-store
    steps:
      - name: Upload extension to Chrome Developer Dashboard
        uses: mobilefirstllc/cws-publish@569e87bc9a54ad7712ba6dc154a110d88af63b85 #v2.1.1
        with:
          action: 'upload'
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: ./extension.zip
