name: Build Chrome Extension ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checko out repo
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node_version: 24
      - name: Install Typescript
        run: npm ci
      - name: Compile Typescript
        run: npm run build
      #- name: Create ZIP
        #run: |
          #zip -r extension.zip . -i "manifest.json" \
          #"popup.html" \
          #"popup.css" \
          #"src/popup.js" \
          #"images" \
          #"_locales"
      #- name: Inspect ZIP
        #run: unzip -l extension.zip
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: |
            manifest.json
            popup.html
            popup.css
            src/popup.js
            images/
            _locales/
